### ISSUE TITLE
IAFD 403 forbidden error

### ISSUE THREAD

**Issue by DrunkSith** [adultmm/AdultMediaManager#121] opened 2024-07-13 14:52 UTC
I can't seem to scrape anything from IAFD.

**Comment by wkearney99** [comment] 2024-07-14 01:46
Same here.  Get error 403 within AMM.  Using same URL in a browser successfully loads the page.

And if I take the title.rme/id= field and use that as a manual ID it also throws the 403 error.

Is the User Agent string editable in AMM?  Might that be something iafd is blocking?

**Comment by wkearney99** [comment] 2024-07-14 11:45
Is this related? https://github.com/adultmm/AdultMediaManager/issues/108#issuecomment-2042704756

> AMM utilizes DuckDuckGo for searches on the IAFD if no results are found during the onsite search. Occasionally, DuckDuckGo blocks too many searches, so AMM attempts accessing DuckDuckGo via the Tor network. However, in your case, this was unsuccessful five times. I'll take a look at the DDG search.

**Comment by adultmm** [comment] 2024-07-14 15:37
Guys, please attach the corresponding log file. Thanks

**Comment by wkearney99** [comment] 2024-07-15 08:01
It's repeatable.  No scrapes are successful from iafd.  This is a simple test.  It has one movie in the database, and ONLY the iafd scraper is enabled.

[2024-07-15.csv](https://github.com/user-attachments/files/16231559/2024-07-15.csv)

**Comment by adultmm** [comment] 2024-07-15 10:00
Thank you. I can see the 403 error in the log, but it works for me. I'll try to reproduce.

**Comment by wkearney99** [comment] 2024-07-15 14:43
It would really help if we had a bit more indications in the log about how a connection was being made.  Using proxies, tor, etc.  It'd help point the finger toward the actual problem.

**Comment by adultmm** [comment] 2024-07-17 08:30
The actual problem - as usual - is the ClouFlare protection. Me, and many others work on solving these challenges:  [FlareSolverr](https://github.com/FlareSolverr/FlareSolverr), [CF-Clearance-Scraper](https://github.com/Xewdy444/CF-Clearance-Scraper/tree/main), etc. If you can download the content of the URL with a curl or any other tool, you have solved the problem. Send the solution, and I'll implement it in AMM.

**Comment by adultmm** [comment] 2024-07-18 12:50
Fixed in [v0.12.12](https://github.com/adultmm/AdultMediaManager/releases/tag/v0.12.12).

**Comment by adultmm** [comment] 2024-07-20 23:54
Try out the standalone version that works: [v1.0.0-beta1](https://github.com/adultmm/AdultMediaManager/releases/tag/v1.0.0-beta1).

**Comment by adultmm** [comment] 2024-07-21 17:31
@wkearney99 @DrunkSith [v1.0.0-beta1](https://github.com/adultmm/AdultMediaManager/releases/tag/v1.0.0-beta1) scrapes IAFD for you? Thanks

**Comment by adultmm** [comment] 2024-07-21 17:46
Cody has an issue with the v1.0.0-beta1 version as well: https://github.com/adultmm/AdultMediaManager/issues/123#issuecomment-2241492370

**Comment by wkearney99** [comment] 2024-07-25 22:39
Nope, 1.0.0.b1 immediate 403 error, same as with 12.11. 
[2024-07-26.csv](https://github.com/user-attachments/files/16395409/2024-07-26.csv)

**Comment by Fetterbr61** [comment] 2024-07-26 06:27
![aaa-004](https://github.com/user-attachments/assets/558941c5-bc0f-4d4a-b01f-30df5a09a446)
cant scrape any japanese movies, especially femdom sites.

**Comment by wkearney99** [comment] 2024-08-06 12:29
The problem seems to come and go.  What's the code logic behind the scenes that would affect this?

**Comment by adultmm** [comment] 2024-08-19 15:22
As I can see, IAFD changed someting on their CF settings and now AMM can scrape their pages.  Please reopen, if the problem appears again.

**Closed as completed by adultmm** 2024-08-19 15:22 UTC
Labels: bug, Cloudflare issue

**Comment by wkearney99** [comment] 2024-10-13 13:54
Seems to be a problem again.  403 errors.  Even a paste of the manual ID entry fails with a 403.
