### ISSUE TITLE
Gay Content

### ISSUE THREAD

**Issue by kalieneris** [adultmm/AdultMediaManager#15] opened 2021-09-30 21:10 UTC
Per the discussion that was started last month, here are two sites that covers what feels like 90% of all gay content (the second also covers straight content). If we could get these, we'd probably be set for most things.

https://www.gayeroticvideoindex.com
https://www.iafd.com/

Also... much appreciation for the build overall.

**Comment by adultmm** [comment] 2022-02-02 16:40
Update: First, I have to implement the "meta-scraper" possibility in my plugin, as Data18 and ThePornDB. It's almost ready. After that, I'll be able to implement these two meta-scrapers as well.

**Comment by kalieneris** [comment] 2022-02-02 19:54
Very cool. Thanks for the update!

**Comment by kalieneris** [comment] 2022-02-24 23:05
Search seems to be working fine for me on both sites. Is there a particular example you can give of it not working or how it should be working that I can look into? Happy to help out in any way.

**Comment by adultmm** [comment] 2022-02-25 09:10
I've figured it out. The Gayeroticvideoindex searches only in movies, not in episodes. I'll use DuckDuckGo.com, as I see it can find lots of videos from the site: https://duckduckgo.com/?q=%22episode%22+site%3Awww.gayeroticvideoindex.com&kp=-2&t=h_&ia=web

**Comment by adultmm** [comment] 2022-03-27 19:17
Update: I implemented the scraper, and I wanted to release it in v0.10.1. But during the last tests, I found that the site had started to use CloudFlare's DDOS protection. My scraper can't handle it yet. I'll work on solving it, but I don't have an estimate for it. Sorry for the bad news.

**Comment by kalieneris** [comment] 2022-03-28 21:03
No worries. Thanks for the update.

**Comment by adultmm** [comment] 2022-05-01 17:17
GayEroticVideoIndex meta-scraper for videos is now available in the [new alpha version](https://github.com/adultmm/AdultMediaManager/releases/tag/v0.11.0-ALPHA.1)

Don't forget to enable it under: Edit > Settings > Movies > AdultScraper > MetaScraper options

Please test it, because I have no content from there. Any remark is very welcome,

**Comment by kalieneris** [comment] 2022-05-02 23:18
So, I ran about a dozen various videos from 3 different studios through and it only managed to correctly find two of them. I wish I could give you better data to figure out what's going on, but nothing really presents itself as the problem that it's facing. I double checked to make sure that all of the videos tested were on the site, that spelling was correct, and I tested various configurations in the search box to see if anything might trigger a correct lookup, but nothing worked. It would come up with other videos in the index as suggestions, but they generally had nothing in common with the search terms, so I'm not sure exactly what it was scraping to find them. If it hadn't found those two videos, I'd say it's doing something completely wrong, but it did find two so... I'm stumped.

If you'd like, I could cloud transfer you a few of them so you have some data to test on your end.

**Comment by adultmm** [comment] 2022-05-03 07:39
Hi @kalieneris,

Thanks for your test. Just give me some filenames with full path and I'll try to solve the problem. 

Thanks

**Comment by kalieneris** [comment] 2022-05-11 02:54
Here are a few examples of filenames that it's not able to scrape and the link to the page on GEVI. I've tried adjusting the filenames to make them more scraper friendly in various configurations, but nothing seems to hit the nail on the head:

[Men At Play] Dr Dani Examines Maikel Cash.mp4
https://gayeroticvideoindex.com/episode/117520

Nextdoorworld - The Reunion - Wet Seduction - Dante Martin And Arad.mp4
https://gayeroticvideoindex.com/episode/128848

RANDY BLUE - Malachi Marx 540P WMA.wmv
https://gayeroticvideoindex.com/episode/103846


As I've been searching for the records on GEVI, I'm wondering if it might have something to do with the way that things are organized over there. To search for scene titles, you need to search for either a performer name or production company name first, and then you can use the second search box to search for scene titles. The main title search box only searches for Movie titles.

Unfortunately, when I ran an actual Movie title to test out that theory, adultmm sent back a bunch of straight results from AdultDVDEmpire instead of any results from GEVI and I'm not sure why. Details for that test are:

Alley Cats (2008) 480p WMA.wmv
https://gayeroticvideoindex.com/video/38475

**Comment by adultmm** [comment] 2022-05-12 08:59
Hi @kalieneris,

You're right, GEVI doesn't find scenes just movies. So I use DDG search engine, to find scenes:

[https://duckduckgo.com/?q=%22Rick+gets+rimmed%22+site%3AGayEroticVideoIndex.com&t=h_&ia=web](https://duckduckgo.com/?q=%22Rick+gets+rimmed%22+site%3AGayEroticVideoIndex.com&t=h_&ia=web)

The problem is, that for your first two titles, DDG found URL like this: 
https://www.gayeroticvideoindex.com/E/117520.html
and my code was looking for like this: https://gayeroticvideoindex.com/episode/117520.html

OK, I'll fix it!

Unfortunately, DDG doesn't find your third scene: 
[[RANDY BLUE - Malachi Marx site:GayEroticVideoIndex.com](https://duckduckgo.com/?q=RANDY+BLUE+-+Malachi+Marx+site%3AGayEroticVideoIndex.com&t=h_&ia=web)](https://duckduckgo.com/?q=RANDY+BLUE+-+Malachi+Marx+site%3AGayEroticVideoIndex.com&t=h_&ia=web)

I have no idea, to solve this for the time being...


GEVI scraper now supports only scenes - as written in the release notes -, supporting movies is a second step. 

Thank you for the tests, I'll come up with the fixes.

**Comment by adultmm** [comment] 2022-05-16 16:26
The above errors have been fixed in [v0.11.0-ALPHA.3](https://github.com/adultmm/AdultMediaManager/releases/tag/v0.11.0-ALPHA.3). 

@kalieneris, please test it again. Thanks

**Comment by kalieneris** [comment] 2022-05-20 01:03
It's certainly working much better. Slow, but usually finding a correct match. But there are still some that it can't find (like the Malachi Marx one you mentioned above) and I can't find any rhyme nor reason why.

Thank you so much for your time and effort on this. The current version is definitely enough to speed up my cataloguing, but if you need any more testing let me know. happy to help.

**Comment by adultmm** [comment] 2022-05-22 17:16
Hi @kalieneris,

Scraping movies with GEVI is also available in [v0.11.0-BETA.1](https://github.com/adultmm/AdultMediaManager/releases/tag/v0.11.0-BETA.1).

I hope, you'll find it useful as well.

Cheers

**Closed** 2022-10-04 17:35 UTC
